requirements_dev.txt: install pymetalink using direct git clone
pymetalink is needed for `make test-notebooks`:

Copying notebook output sanitizer ...
Running notebook-based tests
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /home/lvu/.conda/envs/flyingpigeon/bin/python
cachedir: .pytest_cache
rootdir: /zstore/repos/flyingpigeon, inifile: setup.cfg
plugins: notebook-0.6.0, flake8-1.0.6, nbval-0.9.5
collecting ... collected 16 items

docs/source/notebooks/subset_processes::ipynb::Cell 0 PASSED             [  6%]
docs/source/notebooks/subset_processes::ipynb::Cell 1 PASSED             [ 12%]
docs/source/notebooks/subset_processes::ipynb::Cell 2 PASSED             [ 18%]
docs/source/notebooks/subset_processes::ipynb::Cell 3 PASSED             [ 25%]
docs/source/notebooks/subset_processes::ipynb::Cell 4 FAILED             [ 31%]
docs/source/notebooks/subset_processes::ipynb::Cell 5 PASSED             [ 37%]
docs/source/notebooks/subset_processes::ipynb::Cell 6 PASSED             [ 43%]
docs/source/notebooks/subset_processes::ipynb::Cell 7 PASSED             [ 50%]
docs/source/notebooks/subset_processes::ipynb::Cell 8 PASSED             [ 56%]
docs/source/notebooks/subset_processes::ipynb::Cell 9 PASSED             [ 62%]
docs/source/notebooks/subset_processes::ipynb::Cell 10 FAILED            [ 68%]
docs/source/notebooks/subset_processes::ipynb::Cell 11 FAILED            [ 75%]
docs/source/notebooks/subset_processes::ipynb::Cell 12 FAILED            [ 81%]
docs/source/notebooks/subset_processes::ipynb::Cell 13 PASSED            [ 87%]
docs/source/notebooks/subset_processes::ipynb::Cell 14 PASSED            [ 93%]
docs/source/notebooks/subset_processes::ipynb::Cell 15 PASSED            [100%]

=================================== FAILURES ===================================
_____________ docs/source/notebooks/subset_processes.ipynb::Cell 4 _____________
[91mNotebook cell execution failed[0m
[94mCell 4: Cell outputs differ

Input:
[0m# Enter `fp?` for general exploration on processes provided by flyingpigeon

help(fp.subset_continents) # or type: fp.subset_countries?

[94mTraceback:[0m
[94m mismatch 'stdout'[91m

 assert reference_output == test_output failed:

  'Help on meth... outputs.\n\n' == 'Help on meth... outputs.\n\n'
    Help on method subset_continents in module birdy.client.base:

  - subset_continents(resource=None, region='Africa') method of birdy.client.base.WPSClient instance
  + subset_continents(resource=None, region='Africa', mosaic=False) method of birdy.client.base.WPSClient instance
  ?                                                 ++++++++++++++
        Return the data whose grid cells intersect the selected continents for each input dataset.

        Parameters
        ----------
        region : {'Africa', 'Asia', 'Australia', 'North America', 'Oceania', 'South America', 'Antarctica', 'Europe'}string
            Continent name.
  +     mosaic : boolean
  +         If True, selected regions will be merged into a single geometry.
        resource : ComplexData:mimetype:`application/x-netcdf`, :mimetype:`application/x-tar`, :mimetype:`application/zip`
            NetCDF Files or archive (tar/zip) containing netCDF files.

        Returns
        -------
        output : ComplexData:mimetype:`application/x-netcdf`
            NetCDF output for first resource file.
        metalink : ComplexData:mimetype:`application/metalink+xml; version=4.0`
            Metalink file with links to all NetCDF outputs.

[0m

____________ docs/source/notebooks/subset_processes.ipynb::Cell 10 _____________
[91mNotebook cell execution failed[0m
[94mCell 10: Cell execution caused an exception

Input:
[0m# Run the process
resp = fp_i.subset_continents(resource=urls, region=['Europe', 'Africa'], mosaic=True)

timeout = time.time() + 60*5   # 5 minutes from now

while resp.getStatus() != 'ProcessSucceeded':
    time.sleep(1)
    if time.time() > timeout:  # to avoid endless waiting if the process failed
        break

cont = resp.get()

[94mTraceback:[0m

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-11-ccabe938873f>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Run the process[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mresp[0m [0;34m=[0m [0mfp_i[0m[0;34m.[0m[0msubset_continents[0m[0;34m([0m[0mresource[0m[0;34m=[0m[0murls[0m[0;34m,[0m [0mregion[0m[0;34m=[0m[0;34m[[0m[0;34m'Europe'[0m[0;34m,[0m [0;34m'Africa'[0m[0;34m][0m[0;34m,[0m [0mmosaic[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# using fp_i you need to wait until the processing is complete![0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mtimeout[0m [0;34m=[0m [0mtime[0m[0;34m.[0m[0mtime[0m[0;34m([0m[0;34m)[0m [0;34m+[0m [0;36m60[0m[0;34m*[0m[0;36m5[0m   [0;31m# 5 minutes from now[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: subset_continents() got an unexpected keyword argument 'mosaic'

____________ docs/source/notebooks/subset_processes.ipynb::Cell 11 _____________
[91mNotebook cell execution failed[0m
[94mCell 11: Cell execution caused an exception

Input:
[0m# plot the test file (url of output) with the flyingpigon plot function
resp = fp.plot_map_timemean(resource=cont.output)

[94mTraceback:[0m

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-12-bc56cd51fcc0>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# plot the test file (url of output) with the flyingpigon plot function[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mresp[0m [0;34m=[0m [0mfp[0m[0;34m.[0m[0mplot_map_timemean[0m[0;34m([0m[0mresource[0m[0;34m=[0m[0mcont[0m[0;34m.[0m[0moutput[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'cont' is not defined

____________ docs/source/notebooks/subset_processes.ipynb::Cell 12 _____________
[91mNotebook cell execution failed[0m
[94mCell 12: Cell execution caused an exception

Input:
[0m# The plot process returnes one graphic file.
resp.get(asobj=True).plotout_map

[94mTraceback:[0m

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-13-3203d44d7305>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# The plot process returnes one graphic file.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;31m# It can be plotted directly by asking birdy to get python objects, instead of links to files.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mresp[0m[0;34m.[0m[0mget[0m[0;34m([0m[0masobj[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m.[0m[0mplotout_map[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: 'subset_bboxResponse' object has no attribute 'plotout_map'

=============================== warnings summary ===============================
/home/lvu/.conda/envs/flyingpigeon/lib/python3.7/site-packages/nbval/plugin.py:115
  /home/lvu/.conda/envs/flyingpigeon/lib/python3.7/site-packages/nbval/plugin.py:115: PytestDeprecationWarning: direct construction of IPyNbFile has been deprecated, please use IPyNbFile.from_parent
    return IPyNbFile(path, parent)

/home/lvu/.conda/envs/flyingpigeon/lib/python3.7/site-packages/nbval/plugin.py:312: 16 tests with warnings
  /home/lvu/.conda/envs/flyingpigeon/lib/python3.7/site-packages/nbval/plugin.py:312: PytestDeprecationWarning: direct construction of IPyNbCell has been deprecated, please use IPyNbCell.from_parent
    cell, options)

docs/source/notebooks/subset_processes.ipynb::Cell 0
  /home/lvu/.conda/envs/flyingpigeon/lib/python3.7/site-packages/jupyter_client/manager.py:63: DeprecationWarning: KernelManager._kernel_spec_manager_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
    def _kernel_spec_manager_changed(self):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED docs/source/notebooks/subset_processes.ipynb::Cell 4
FAILED docs/source/notebooks/subset_processes.ipynb::Cell 10
FAILED docs/source/notebooks/subset_processes.ipynb::Cell 11
FAILED docs/source/notebooks/subset_processes.ipynb::Cell 12
================== 4 failed, 12 passed, 18 warnings in 12.76s ==================
Makefile:125: recipe for target 'test-notebooks' failed.