fix pymetalink install link in requirements_dev.txt broke make develop
Had to move it out of requirements_dev.txt and into make develop itself
as a work-around.

Below is error when pymetalink install link is in requirements_dev.txt:
```
$ make develop
Installing development requirements for tests and docs ...
Obtaining file:///zstore/repos/flyingpigeon
    ERROR: Command errored out with exit status 1:
     command: /home/lvu/.conda/envs/flyingpigeon/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/zstore/repos/flyingpigeon/set
up.py'"'"'; __file__='"'"'/zstore/repos/flyingpigeon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n
'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qqaszq3v
         cwd: /zstore/repos/flyingpigeon/
    Complete output (1 lines):
    error in flyingpigeon setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/v
ersion requirement specifiers.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```