doc: can not monkeypatch something that do not exist
numpy existed in Raven because we install xclim in Raven.

$ make docs
Generating docs with Sphinx ...
make[1]: Entering directory '/zstore/repos/flyingpigeon/docs'
Removing everything under 'build'...
Running Sphinx v3.1.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/lvu/.conda/envs/flyingpigeon-docs/lib/python3.7/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/home/lvu/.conda/envs/flyingpigeon-docs/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/zstore/repos/flyingpigeon/docs/source/conf.py", line 71, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'

Makefile:20: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/zstore/repos/flyingpigeon/docs'
Makefile:147: recipe for target 'docs' failed
make: *** [docs] Error 2