Travis-CI: disable doc build for python 3.6, 3.7 works fine
ReadTheDocs is 3.7 so that's what matter.

Warning, treated as error:
autodoc: failed to import process 'processes.wps_pointinspection.PointinspectionProcess' from module 'flyingpigeon'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/flyingpigeon/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/travis/miniconda/envs/flyingpigeon/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/bird-house/flyingpigeon/flyingpigeon/__init__.py", line 7, in <module>
    from .wsgi import application  # noqa: F401
  File "/home/travis/build/bird-house/flyingpigeon/flyingpigeon/wsgi.py", line 4, in <module>
    from .processes import processes
  File "/home/travis/build/bird-house/flyingpigeon/flyingpigeon/processes/__init__.py", line 8, in <module>
    from .wps_spatial_analog import SpatialAnalogProcess
  File "/home/travis/build/bird-house/flyingpigeon/flyingpigeon/processes/wps_spatial_analog.py", line 27, in <module>
    from flyingpigeon.ocgisDissimilarity import Dissimilarity, metrics
  File "/home/travis/build/bird-house/flyingpigeon/flyingpigeon/ocgisDissimilarity.py", line 13, in <module>
    class Dissimilarity(AbstractFieldFunction, AbstractParameterizedFunction):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases