requirement_dev.txt: comment out pymetalink
See Travis-CI logs: https://api.travis-ci.org/v3/job/692554776/log.txt
(https://travis-ci.org/github/bird-house/flyingpigeon/jobs/692554776#L1405)

Fail make develop:

```
RROR: Could not find a version that satisfies the requirement pymetalink (from flyingpigeon==1.5.1) (from versions: none)
ERROR: No matching distribution found for pymetalink (from flyingpigeon==1.5.1)
Makefile:50: recipe for target 'develop' failed
make: [develop] Error 1 (ignored)
```

Which in turn fail make test-notebooks because the pip install in make develop did not finish:

```
$ make test-notebooks
Copying notebook output sanitizer ...
Running notebook-based tests
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --nbval --sanitize-with /home/travis/build/bird-house/flyingpigeon/docs/source/output-sanitize.cfg
  inifile: /home/travis/build/bird-house/flyingpigeon/setup.cfg
  rootdir: /home/travis/build/bird-house/flyingpigeon
Makefile:125: recipe for target 'test-notebooks' failed
```

```
$ make docs
Generating docs with Sphinx ...
make[1]: Entering directory '/home/travis/build/bird-house/flyingpigeon/docs'
Running Sphinx v3.0.4
Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
Makefile:20: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/travis/build/bird-house/flyingpigeon/docs'
Makefile:142: recipe for target 'docs' failed
make: [docs] Error 2 (ignored)
```